### ISSUE TITLE
launch checks fail for cob_controller_configuration_gazebo

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/cob_robots#143]
running make test in cob_controller_configuration_gazebo fails. error see below.

checking ros/launch/default_controllers_cob3-5.launch
Traceback (most recent call last):
  File "/opt/ros/groovy/share/roslaunch/scripts/roslaunch-check", line 85, in <module>
    error_msg = check_roslaunch_file(roslaunch_path)
  File "/opt/ros/groovy/share/roslaunch/scripts/roslaunch-check", line 45, in check_roslaunch_file
    error_msg = roslaunch.rlutil.check_roslaunch(roslaunch_file)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/rlutil.py", line 199, in check_roslaunch
    base_pkg, file_deps, missing = roslaunch.depends.roslaunch_deps([f])
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/depends.py", line 304, in roslaunch_deps
    rl_file_deps(file_deps, launch_file, verbose)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/depends.py", line 212, in rl_file_deps
    parse_launch(launch_file, file_deps, verbose)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/depends.py", line 197, in parse_launch
    _parse_launch(launch_tag.childNodes, launch_file, file_deps, verbose, context)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/depends.py", line 135, in _parse_launch
    v = _parse_arg(tag, context)
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/depends.py", line 108, in _parse_arg
    return (name, _get_arg_value(tag, context))
  File "/opt/ros/groovy/lib/python2.7/dist-packages/roslaunch/depends.py", line 95, in _get_arg_value
    raise RoslaunchDepsException("No value for arg [%s]"%(name))
roslaunch.depends.RoslaunchDepsException: No value for arg [robot]
make[4]: **\* [CMakeFiles/roslaunch_check_ros_launch_default_controllers_cob3-5.launch_5] Error 1
make[4]: Target `CMakeFiles/roslaunch_check_ros_launch_default_controllers_cob3-5.launch_5.dir/build' not remade because of errors.
make[4]: Leaving directory`/tmp/src/dry/cob_robots/cob_controller_configuration_gazebo/build'
make[3]: **\* [CMakeFiles/roslaunch_check_ros_launch_default_controllers_cob3-5.launch_5.dir/all] Error 2
make[4]: Entering directory `/tmp/src/dry/cob_robots/cob_controller_configuration_gazebo/build'
make[4]: Leaving directory`/tmp/src/dry/cob_robots/cob_controller_configuration_gazebo/build'
make[4]: Entering directory `/tmp/src/dry/cob_robots/cob_controller_configuration_gazebo/build'

**Comment by fmessmer** [comment]
should be fixed by adding default values 
(see https://github.com/ipa-fxm/cob_robots/commit/7af9e7c7fbe4600e1def90ee30ecb3b3fd13d9ed)

However, how do rostest launch file checks work? Can't you specify a value for the arguments for each check?
Because we also have several other launch files with launch file arguments, where a default value does not make sense (e.g. the new generic_controller.launch files)

**Comment by floweisshardt** [comment]
we should not put in default values if they make no sense. The workaround is to exclude the files where we need launch arguments without default from the roslaunch tests by renaming them to *.xml. Example see cob_bringup.

**Comment by fmessmer** [comment]
I think this is no longer an issue as all tests pass with #279 
Thus, I think we can close this!
