### ISSUE TITLE
cob3-9 URDF broken

### ISSUE THREAD

**Issue by floweisshardt** [ipa320/cob_robots#552]
from travis (`Parameters [has_podest] were not set for macro xacro:schunk_pg70`):
```
  /usr/bin/cmake -E make_directory /home/travis/catkin_ws/build/test_results/cob_bringup

  /opt/ros/indigo/share/roslaunch/cmake/../scripts/roslaunch-check -o /home/travis/catkin_ws/build/test_results/cob_bringup/roslaunch-check_cob3-9__ROBOT_ENV_ipa-factory.xml.xml /home/travis/catkin_ws/src/cob_robots/cob_bringup/robots/cob3-9.xml ROBOT_ENV=ipa-factory

checking /home/travis/catkin_ws/src/cob_robots/cob_bringup/robots/cob3-9.xml

Traceback (most recent call last):

  File "/opt/ros/indigo/share/xacro/xacro.py", line 62, in <module>

    xacro.main()

  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 696, in main

    eval_self_contained(doc)

  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 626, in eval_self_contained

    eval_all(doc.documentElement, macros, symbols)

  File "/opt/ros/indigo/lib/python2.7/dist-packages/xacro/__init__.py", line 552, in eval_all

    (",".join(params), str(node.tagName)))

xacro.XacroException: Parameters [has_podest] were not set for macro xacro:schunk_pg70

...writing test results to /home/travis/catkin_ws/build/test_results/cob_bringup/roslaunch-check_cob3-9__ROBOT_ENV_ipa-factory.xml.xml

FAILURE:

[/home/travis/catkin_ws/src/cob_robots/cob_bringup/robots/cob3-9.xml]:

	while processing /home/travis/catkin_ws/src/cob_robots/cob_hardware_config/common/upload_robot.launch:

Invalid <param> tag: Cannot load command parameter [robot_description]: command [/opt/ros/indigo/share/xacro/xacro.py '/home/travis/catkin_ws/src/cob_robots/cob_hardware_config/cob3-9/urdf/cob3-9.urdf.xacro'] returned with code [1]. 
```

**Comment by floweisshardt** [comment]
fixed in #553
